<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>name</key>
		<string>Terbium</string>
		<key>scopeName</key>
		<string>source.terbium</string>
		<key>fileTypes</key>
		<array>
			<string>tb</string>
			<string>trb</string>
			<string>terbium</string>
		</array>
		<key>foldingStartMarker</key>
		<string>\{\s*$</string>
		<key>foldingStopMarker</key>
		<string>^\s*\}</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#root</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>root</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#import</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#func_def</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#struct_inner</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#concrete_def</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#const_def</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#alias_def</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#type_alias_def</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#vis</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>\blet\b</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.declaration.let.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=[;=])</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>begin</key>
								<string>:</string>
								<key>beginCaptures</key>
								<array>
									<dict>
										<key>name</key>
										<string>punctuation.separator.type.terbium</string>
									</dict>
								</array>
								<key>end</key>
								<string>(?=[;=])</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#ty</string>
									</dict>
								</array>
							</dict>
							<dict>
								<key>include</key>
								<string>#pat</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>\bfor\b</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.control.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>\bin\b</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.control.terbium</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#pat</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>include</key>
						<string>#atom</string>
					</dict>
				</array>
			</dict>
			<key>block_doc_comment</key>
			<dict>
				<key>comment</key>
				<string>Block documentation comment</string>
				<key>name</key>
				<string>comment.block.documentation.terbium</string>
				<key>begin</key>
				<string>/\*[\*!](?![\*/])</string>
				<key>end</key>
				<string>\*/</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#block_doc_comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#block_comment</string>
					</dict>
				</array>
			</dict>
			<key>block_comment</key>
			<dict>
				<key>comment</key>
				<string>Block comment</string>
				<key>name</key>
				<string>comment.block.terbium</string>
				<key>begin</key>
				<string>/\*</string>
				<key>end</key>
				<string>\*/</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#block_doc_comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#block_comment</string>
					</dict>
				</array>
			</dict>
			<key>line_doc_comment</key>
			<dict>
				<key>comment</key>
				<string>Single-line documentation comment</string>
				<key>name</key>
				<string>comment.line.documentation.terbium</string>
				<key>begin</key>
				<string>//[!/](?=[^/])</string>
				<key>end</key>
				<string>$</string>
			</dict>
			<key>line_comment</key>
			<dict>
				<key>comment</key>
				<string>Single-line comment</string>
				<key>name</key>
				<string>comment.line.double-slash.terbium</string>
				<key>begin</key>
				<string>//</string>
				<key>end</key>
				<string>$</string>
			</dict>
			<key>comment</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#block_doc_comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#block_comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#line_doc_comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#line_comment</string>
					</dict>
				</array>
			</dict>
			<key>decimal_literal</key>
			<dict>
				<key>name</key>
				<string>constant.numeric.integer.decimal.terbium</string>
				<key>match</key>
				<string>\b[0-9][0-9_]*u?\b</string>
			</dict>
			<key>hex_literal</key>
			<dict>
				<key>name</key>
				<string>constant.numeric.integer.hexadecimal.terbium</string>
				<key>match</key>
				<string>\b0x[0-9a-fA-F][0-9a-fA-F_]*u?\b</string>
			</dict>
			<key>oct_literal</key>
			<dict>
				<key>name</key>
				<string>constant.numeric.integer.octal.terbium</string>
				<key>match</key>
				<string>\b0o[0-7][0-7_]*u?\b</string>
			</dict>
			<key>bin_literal</key>
			<dict>
				<key>name</key>
				<string>constant.numeric.integer.binary.terbium</string>
				<key>match</key>
				<string>\b0b[01][01_]*u?\b</string>
			</dict>
			<key>int_literal</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#hex_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#oct_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#bin_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#decimal_literal</string>
					</dict>
				</array>
			</dict>
			<key>float_literal</key>
			<dict>
				<key>name</key>
				<string>constant.numeric.float.terbium</string>
				<key>match</key>
				<string>\b(?:[0-9][0-9_]*(?:\.[0-9][0-9_]*)?[Ee][+-]?[0-9]+|[0-9][0-9_]*\.[0-9][0-9_]*)\b</string>
			</dict>
			<key>bool_literal</key>
			<dict>
				<key>comment</key>
				<string>Boolean constant</string>
				<key>name</key>
				<string>constant.language.boolean.terbium</string>
				<key>match</key>
				<string>\b(true|false)\b</string>
			</dict>
			<key>void_literal</key>
			<dict>
				<key>comment</key>
				<string>Void constant</string>
				<key>name</key>
				<string>constant.language.void.terbium</string>
				<key>match</key>
				<string>\bvoid\b</string>
			</dict>
			<key>self</key>
			<dict>
				<key>comment</key>
				<string>Self variable</string>
				<key>name</key>
				<string>variable.language.terbium</string>
				<key>match</key>
				<string>\bself\b</string>
			</dict>
			<key>self_ty</key>
			<dict>
				<key>name</key>
				<string>variable.language.type.terbium</string>
				<key>match</key>
				<string>\bSelf\b</string>
			</dict>
			<key>kw_control</key>
			<dict>
				<key>comment</key>
				<string>Control keyword</string>
				<key>name</key>
				<string>keyword.control.terbium</string>
				<key>match</key>
				<string>\b(break|continue|else|if|then|loop|return|while|catch)\b</string>
			</dict>
			<key>kw_operator</key>
			<dict>
				<key>comment</key>
				<string>Operator keyword</string>
				<key>name</key>
				<string>keyword.operator.word.terbium</string>
				<key>match</key>
				<string>\b(to|is)\b</string>
			</dict>
			<key>kw_static</key>
			<dict>
				<key>comment</key>
				<string>Static keyword</string>
				<key>name</key>
				<string>storage.modifier.static.terbium</string>
				<key>match</key>
				<string>\bstatic\b</string>
			</dict>
			<key>primitive_ty</key>
			<dict>
				<key>comment</key>
				<string>Primitive type</string>
				<key>name</key>
				<string>storage.type.primitive.terbium</string>
				<key>match</key>
				<string>\b(u?int(?:8|16|32|64|128|ptr)?|float(?:32|64|128)?|bool|char|string|void|never)\b</string>
			</dict>
			<key>reserved</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#bool_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#void_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#self</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#self_ty</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#mut</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#kw_control</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#kw_operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#kw_const</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#kw_static</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#primitive_ty</string>
					</dict>
				</array>
			</dict>
			<key>ident</key>
			<dict>
				<key>name</key>
				<string>variable.other.terbium</string>
				<key>match</key>
				<string>\b(?:[a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\b</string>
			</dict>
			<key>escape_seq</key>
			<dict>
				<key>name</key>
				<string>constant.character.escape.terbium</string>
				<key>match</key>
				<string>\\(?:[0-7]{1,3}|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[abfnrtv'"?\\])</string>
			</dict>
			<key>standard_string_literal</key>
			<dict>
				<key>comment</key>
				<string>Double-quote string literal</string>
				<key>name</key>
				<string>string.quoted.terbium</string>
				<key>begin</key>
				<string>(#*)(['"])</string>
				<key>end</key>
				<string>\2\1</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#escape_seq</string>
					</dict>
				</array>
			</dict>
			<key>raw_string_literal</key>
			<dict>
				<key>name</key>
				<string>string.quoted.terbium</string>
				<key>begin</key>
				<string>\~(#*)(['"])</string>
				<key>end</key>
				<string>\2\1</string>
			</dict>
			<key>interpolation</key>
			<dict>
				<key>name</key>
				<string>string.interpolated.terbium</string>
				<key>begin</key>
				<string>\{</string>
				<key>beginCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.embedded.terbium</string>
					</dict>
				</array>
				<key>end</key>
				<string>\}</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.embedded.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#atom</string>
					</dict>
				</array>
			</dict>
			<key>interpolated_string_literal</key>
			<dict>
				<key>name</key>
				<string>string.quoted.terbium</string>
				<key>begin</key>
				<string>\$(#*)(['"])</string>
				<key>end</key>
				<string>\2\1</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#escape_seq</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#interpolation</string>
					</dict>
				</array>
			</dict>
			<key>interpolated_raw_string_literal</key>
			<dict>
				<key>name</key>
				<string>string.quoted.terbium</string>
				<key>begin</key>
				<string>(?:\~\$|\$\~)(#*)(['"])</string>
				<key>end</key>
				<string>\2\1</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#interpolation</string>
					</dict>
				</array>
			</dict>
			<key>string_literal</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#interpolated_raw_string_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#interpolated_string_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#raw_string_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#standard_string_literal</string>
					</dict>
				</array>
			</dict>
			<key>char_literal</key>
			<dict>
				<key>name</key>
				<string>constant.character.terbium</string>
				<key>match</key>
				<string>c(['"])(\\(?:[0-7]{1,3}|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[abfnrtv'"?\\])|.)\1</string>
				<key>captures</key>
				<dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>constant.character.escape.terbium</string>
					</dict>
				</dict>
			</dict>
			<key>when</key>
			<dict>
				<key>name</key>
				<string>meta.when.terbium</string>
				<key>begin</key>
				<string>(\bwhen)\s*(\{)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.braces.begin.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\}</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.braces.end.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>keyword.operator.diverge.terbium</string>
						<key>match</key>
						<string>-&gt;</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#atom</string>
					</dict>
				</array>
			</dict>
			<key>match</key>
			<dict>
				<key>name</key>
				<string>meta.match.terbium</string>
				<key>begin</key>
				<string>\b(match)\s+</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\}</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.braces.end.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>(?&lt;=\bmatch\s+)</string>
						<key>end</key>
						<string>(?=\{)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atom</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.match-arms.terbium</string>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.braces.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\})</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>name</key>
								<string>meta.arm.terbium</string>
								<key>end</key>
								<string>(?=[,\}])</string>
								<key>begin</key>
								<string>(?&lt;=[,\{])</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>name</key>
										<string>meta.arm.else.terbium</string>
										<key>begin</key>
										<string>\s*(else)\b</string>
										<key>beginCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.terbium</string>
											</dict>
										</dict>
										<key>end</key>
										<string>(?=[,\}])</string>
										<key>patterns</key>
										<array>
											<dict>
												<key>include</key>
												<string>#atom</string>
											</dict>
										</array>
									</dict>
									<dict>
										<key>name</key>
										<string>meta.arm.condition.terbium</string>
										<key>begin</key>
										<string>\bif\b</string>
										<key>beginCaptures</key>
										<array>
											<dict>
												<key>name</key>
												<string>keyword.control.terbium</string>
											</dict>
										</array>
										<key>end</key>
										<string>(?=-&gt;)</string>
										<key>patterns</key>
										<array>
											<dict>
												<key>include</key>
												<string>#atom</string>
											</dict>
										</array>
									</dict>
									<dict>
										<key>name</key>
										<string>meta.arm.diverge.terbium</string>
										<key>begin</key>
										<string>-&gt;</string>
										<key>beginCaptures</key>
										<array>
											<dict>
												<key>name</key>
												<string>keyword.operator.diverge.terbium</string>
											</dict>
										</array>
										<key>end</key>
										<string>(?=[,\}])</string>
										<key>patterns</key>
										<array>
											<dict>
												<key>include</key>
												<string>#atom</string>
											</dict>
										</array>
									</dict>
									<dict>
										<key>match</key>
										<string>\s+$</string>
									</dict>
									<dict>
										<key>name</key>
										<string>meta.arm.pattern.terbium</string>
										<key>begin</key>
										<string>(?&lt;=[,\{])|^\s*</string>
										<key>end</key>
										<string>(?=\bif\b|-&gt;|\})</string>
										<key>patterns</key>
										<array>
											<dict>
												<key>include</key>
												<string>#pat</string>
											</dict>
										</array>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>atom</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#float_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#int_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#reserved</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#char_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#when</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#match</string>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.function-call.terbium</string>
						<key>begin</key>
						<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\s*((?&lt;ang&gt;\&lt;(?:(?&gt;[^&lt;&gt;]+)|\g&lt;ang&gt;)*\&gt;))?\s*(\()</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.function.terbium</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.generic.terbium</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#generic_application</string>
									</dict>
								</array>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.parens.begin.terbium</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\)</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.parens.end.terbium</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atom</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>entity.name.label</string>
						<key>match</key>
						<string>:([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\b</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#ident</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.terbium</string>
						<key>match</key>
						<string>\.\.=?</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\?\.</string>
						<key>name</key>
						<string>punctuation.accessor.optional.terbium</string>
					</dict>
					<dict>
						<key>name</key>
						<string>punctuation.accessor.terbium</string>
						<key>match</key>
						<string>\.</string>
					</dict>
					<dict>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
						<key>match</key>
						<string>,</string>
					</dict>
					<dict>
						<key>name</key>
						<string>punctuation.terminator.terbium</string>
						<key>match</key>
						<string>;</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.terbium</string>
						<key>match</key>
						<string>[!=]=|(\+|\-|\*\*?|/|%|\|\|?|&amp;&amp;?|\^|~|!|&lt;&lt;?|&gt;&gt;?)=?|\|&gt;</string>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.block.terbium</string>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>\}</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.end.terbium</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#root</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>type</key>
			<dict>
				<key>comment</key>
				<string>Type</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#primitive_ty</string>
					</dict>
					<dict>
						<key>name</key>
						<string>storage.modifier.mutable.terbium</string>
						<key>match</key>
						<string>\bmut\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>storage.modifier.ref.terbium</string>
						<key>match</key>
						<string>\bref\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.to.terbium</string>
						<key>match</key>
						<string>\bto\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.throws.terbium</string>
						<key>match</key>
						<string>\bthrows\b</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#self_ty</string>
					</dict>
					<dict>
						<key>name</key>
						<string>variable.other.type.terbium</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#ident</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>include</key>
						<string>#int_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#generic_application</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\.</string>
						<key>name</key>
						<string>punctuation.accessor.terbium</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\?</string>
						<key>name</key>
						<string>keyword.operator.optional.terbium</string>
					</dict>
				</array>
			</dict>
			<key>generic_application</key>
			<dict>
				<key>comment</key>
				<string>Generic type application</string>
				<key>begin</key>
				<string>&lt;</string>
				<key>beginCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.generic.begin.terbium</string>
					</dict>
				</array>
				<key>end</key>
				<string>&gt;</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.generic.end.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#type</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
					</dict>
					<dict>
						<key>match</key>
						<string>=</string>
						<key>name</key>
						<string>punctuation.definition.terbium</string>
					</dict>
				</array>
			</dict>
			<key>type_param</key>
			<dict>
				<key>comment</key>
				<string>Generic type parameter</string>
				<key>begin</key>
				<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\s*(:)?</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>variable.language.generic-parameter.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.separator.type.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=[,&gt;])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#type</string>
					</dict>
				</array>
			</dict>
			<key>type_params</key>
			<dict>
				<key>name</key>
				<string>meta.type_params.terbium</string>
				<key>begin</key>
				<string>&lt;(?!&lt;)</string>
				<key>beginCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.generic.begin.terbium</string>
					</dict>
				</array>
				<key>end</key>
				<string>&gt;</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.generic.end.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#type_param</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
					</dict>
					<dict>
						<key>match</key>
						<string>=</string>
						<key>name</key>
						<string>punctuation.definition.terbium</string>
					</dict>
				</array>
			</dict>
			<key>pat_ident</key>
			<dict>
				<key>comment</key>
				<string>Binding</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(mut)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.modifier.mutable.terbium</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>variable.other.readwrite.terbium</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\b</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.other.terbium</string>
							</dict>
						</dict>
					</dict>
				</array>
			</dict>
			<key>pat_tuple</key>
			<dict>
				<key>comment</key>
				<string>Tuple binding</string>
				<key>begin</key>
				<string>\(</string>
				<key>beginCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.begin.terbium</string>
					</dict>
				</array>
				<key>end</key>
				<string>\)</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.end.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#pat</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
					</dict>
				</array>
			</dict>
			<key>pat_rest</key>
			<dict>
				<key>comment</key>
				<string>Rest</string>
				<key>match</key>
				<string>\*</string>
				<key>name</key>
				<string>constant.language.wildcard.terbium</string>
			</dict>
			<key>pat_as</key>
			<dict>
				<key>match</key>
				<string>\b(as)\s+((?:mut\s+)?(?:[a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`))</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.as.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>(mut)\s+(.+)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>storage.modifier.mutable.terbium</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable.other.readwrite.terbium</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>.+</string>
								<key>name</key>
								<string>variable.other.terbium</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>pat</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#int_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#float_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#string_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#char_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#bool_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#void_literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#pat_as</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#pat_ident</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#pat_tuple</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#pat_rest</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\.\.=?</string>
						<key>name</key>
						<string>keyword.operator.range.terbium</string>
					</dict>
				</array>
			</dict>
			<key>pat_ident_func</key>
			<dict>
				<key>comment</key>
				<string>Binding</string>
				<key>match</key>
				<string>(\bmut\s+)?([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.modifier.mutable.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>variable.parameter.terbium</string>
					</dict>
				</dict>
			</dict>
			<key>pat_tuple_func</key>
			<dict>
				<key>comment</key>
				<string>Tuple binding</string>
				<key>begin</key>
				<string>\(</string>
				<key>beginCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.begin.terbium</string>
					</dict>
				</array>
				<key>end</key>
				<string>\)</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.end.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#pat_func</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
					</dict>
				</array>
			</dict>
			<key>pat_as_func</key>
			<dict>
				<key>match</key>
				<string>\b(as)\s+((?:mut\s+)?[a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.as.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>variable.parameter.terbium</string>
					</dict>
				</dict>
			</dict>
			<key>pat_func</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#pat_as_func</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#pat_ident_func</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#pat_tuple_func</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#pat_rest</string>
					</dict>
				</array>
			</dict>
			<key>vis</key>
			<dict>
				<key>comment</key>
				<string>Visibility</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>(public)(\()</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.modifier.visibility.terbium</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.parameters.begin.terbium</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\)</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.parameters.end.terbium</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>pubilc|lib|super|mod|sub|private</string>
								<key>name</key>
								<string>storage.modifier.visibility.terbium</string>
							</dict>
							<dict>
								<key>match</key>
								<string>[gs]et</string>
								<key>name</key>
								<string>keyword.other.terbium</string>
							</dict>
							<dict>
								<key>match</key>
								<string>,</string>
								<key>name</key>
								<string>punctuation.separator.terbium</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>storage.modifier.visibility.terbium</string>
						<key>match</key>
						<string>\b(public|private)\b</string>
					</dict>
				</array>
			</dict>
			<key>const_def</key>
			<dict>
				<key>comment</key>
				<string>Constant definition</string>
				<key>begin</key>
				<string>(const)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\b</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.declaration.constant.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.constant.terbium, variable.other.constant.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\=</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.definition.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>:</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.separator.type.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\=)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>alias_def</key>
			<dict>
				<key>comment</key>
				<string>Alias definition</string>
				<key>begin</key>
				<string>\b(alias)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.declaration.alias.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.constant.terbium, variable.other.constant.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>=</string>
			</dict>
			<key>func_def</key>
			<dict>
				<key>name</key>
				<string>meta.definition.function.terbium</string>
				<key>comment</key>
				<string>Function definition</string>
				<key>begin</key>
				<string>(\bop\s+)?\b(func)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.modifier.operation.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.declaration.function.terbium</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>[\};]</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.terminator.terbium</string>
								<key>match</key>
								<string>;</string>
							</dict>
							<dict>
								<key>name</key>
								<string>punctuation.definition.terbium</string>
								<key>match</key>
								<string>=</string>
							</dict>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.terbium</string>
								<key>match</key>
								<string>\{</string>
							</dict>
						</array>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#type_params</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>\(</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.parameters.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>\)</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.parameters.end.terbium</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#self</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#pat_func</string>
							</dict>
							<dict>
								<key>match</key>
								<string>,</string>
								<key>name</key>
								<string>punctuation.separator.terbium</string>
							</dict>
							<dict>
								<key>begin</key>
								<string>:</string>
								<key>beginCaptures</key>
								<array>
									<dict>
										<key>name</key>
										<string>punctuation.separator.type.terbium</string>
									</dict>
								</array>
								<key>end</key>
								<string>(?=,|\))</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#type</string>
									</dict>
								</array>
							</dict>
							<dict>
								<key>begin</key>
								<string>=</string>
								<key>beginCaptures</key>
								<array>
									<dict>
										<key>name</key>
										<string>keyword.operator.assignment.terbium</string>
									</dict>
								</array>
								<key>end</key>
								<string>(?=,|\))</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#atom</string>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>-&gt;</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.operator.returns.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\{|;|=)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\})</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#root</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>=</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.definition.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=;)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atom</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>type_alias_def</key>
			<dict>
				<key>begin</key>
				<string>\b(type)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.declaration.type.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>;</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.terminator.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#type_params</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>=</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.separator.type.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=;)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>concrete_header</key>
			<dict>
				<key>name</key>
				<string>meta.concrete-header.terbium</string>
				<key>begin</key>
				<string>(?&lt;=(\b(?:struct|enum))\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`))</string>
				<key>end</key>
				<string>(?=\{|;)</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#type_params</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>:</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.separator.type.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\{|;)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>struct_field</key>
			<dict>
				<key>begin</key>
				<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\b</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>variable.other.member.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>,|(?=\}|\bfunc\b)</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
						<key>match</key>
						<string>,</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>:</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.separator.type.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\=|,|\})</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>=</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.operator.assignment.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=,|\})</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atom</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>enum_field</key>
			<dict>
				<key>begin</key>
				<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\b</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>variable.other.member.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>,|(?=\}|\bfunc\b)</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
						<key>match</key>
						<string>,</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>begin</key>
						<string>\(</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>\)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.section.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>\}</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.section.end.terbium</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#struct_field</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>=</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>keyword.operator.assignment.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=,|\})</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#atom</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>struct_def</key>
			<dict>
				<key>name</key>
				<string>meta.definition.type.terbium</string>
				<key>begin</key>
				<string>(\bstruct)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.declaration.struct.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.struct.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\}|;</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.end.terbium</string>
								<key>match</key>
								<string>\}</string>
							</dict>
							<dict>
								<key>name</key>
								<string>punctuation.terminator.terbium</string>
								<key>match</key>
								<string>;</string>
							</dict>
						</array>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#concrete_header</string>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.fields.terbium</string>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\})</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#comment</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#vis</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#func_def</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#struct_field</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>enum_def</key>
			<dict>
				<key>name</key>
				<string>meta.definition.type.terbium</string>
				<key>begin</key>
				<string>(\benum)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.declaration.enum.terbium</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.enum.terbium</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\}</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.section.block.end.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#concrete_header</string>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.fields.terbium</string>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.block.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>(?=\})</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#comment</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#vis</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#func_def</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#enum_field</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>concrete_def</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#struct_def</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#enum_def</string>
					</dict>
				</array>
			</dict>
			<key>import_inner</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>punctuation.separator.terbium</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\.</string>
						<key>name</key>
						<string>punctuation.accessor.terbium</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\*</string>
						<key>name</key>
						<string>constant.language.wildcard.terbium</string>
					</dict>
					<dict>
						<key>match</key>
						<string>self|super|lib</string>
						<key>name</key>
						<string>variable.language.terbium</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\.</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.other.module.terbium</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)\s*(as)\s+([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.other.module.terbium</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.control.import.terbium</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>entity.name.import.terbium</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>match</key>
						<string>\b([a-zA-Z_][a-zA-Z0-9_]*|`[^\n\r`]+`)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>entity.name.import.terbium</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>begin</key>
						<string>\{</string>
						<key>beginCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.import.begin.terbium</string>
							</dict>
						</array>
						<key>end</key>
						<string>\}</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.section.import.end.terbium</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#import_inner</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>import</key>
			<dict>
				<key>name</key>
				<string>meta.import.terbium</string>
				<key>begin</key>
				<string>\bimport\b</string>
				<key>beginCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>keyword.control.import.terbium</string>
					</dict>
				</array>
				<key>end</key>
				<string>;</string>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.terminator.terbium</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#import_inner</string>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
</plist>
